name: sublay
description: "Ứng dụng xem video YouTube với phụ đề SRT tùy chỉnh - SubLay"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # UI Components
  getwidget: ^6.0.0
  cached_network_image: ^3.3.1
  google_nav_bar: ^5.0.6

  # Icons
  flutter_svg: ^2.0.10+1
  iconsax: ^0.0.8

  # State Management & Navigation
  get: ^4.6.6

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2

  # UI Enhancements
  shimmer: ^3.0.0
  liquid_pull_to_refresh: ^3.0.1
  smooth_page_indicator: ^1.1.0
  auto_size_text: ^3.0.0

  # Responsive & Layout
  flutter_screenutil: ^5.9.3
  responsive_builder: ^0.7.0
  flutter_layout_grid: ^2.0.7

  # Video & YouTube
  youtube_player_iframe: 5.2.1
  video_player: ^2.8.6

  # File & SRT Processing
  file_picker: ^8.0.6
  permission_handler: ^11.3.1
  subtitle: ^0.1.4

  # Utilities
  connectivity_plus: ^6.0.3
  url_launcher: ^6.2.6
  path_provider: ^2.1.3

  # Network
  dio: ^5.4.3+1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code generation cho Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

  # App icon generator
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#FF0000"
    theme_color: "#3182CE"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"
